### ISSUE TITLE
[Bug]: party bug 

### ISSUE THREAD

**Issue by stony5** [CMGStudios/minigames-issue-tracker#10] opened 2022-06-19 09:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

get the party leader to leave and get then to go in another lobby it puts you in the lobby then it makes you leave then it say your in a lobby already then you have to relog  clip - https://youtu.be/_BWk6J2-skU

### Expected behaviour

should put in the lobby with them 

### Steps to reproduce

get the party leader to leave 
then get them to join another lobby 
then it bug out then you have to relog  

### CMG User ID

135

**Comment by crazychris2404** [comment] 2022-06-19 10:16
Confirmed
In more detail
If the party leader leaves and goes into a new game everyone's game glitches due to being taken out of current game and put into new one which party leader joins

**Comment by crazychris2404** [comment] 2022-06-19 11:26
This should be resolved within the following update
https://canary.discord.com/channels/939537628326395994/942005453641105408/988041773936943124

**Closed as completed by crazychris2404** 2022-06-19 11:26 UTC
Labels: bug, fixed
